# Generated by Django 4.0.3 on 2022-03-16 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Аллергия')),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Предпочтения')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название продукта')),
            ],
            options={
                'verbose_name': 'Ингридиент',
                'verbose_name_plural': 'Ингридиенты',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=250, verbose_name='Фамилия')),
                ('chat_id', models.IntegerField(unique=True, verbose_name='Chat id')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Подписчик',
                'verbose_name_plural': 'Подписчики',
            },
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('number_of_meals', models.PositiveSmallIntegerField(verbose_name='Количество приемов пищи в день')),
                ('subscription_period', models.DateField(blank=True, null=True, verbose_name='Срок действия подписки')),
                ('allergy', models.ManyToManyField(related_name='subscribes', to='tgbot.allergy', verbose_name='Аллергии')),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribes', to='tgbot.preference', verbose_name='Предпочтения')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribes', to='tgbot.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписчик',
                'verbose_name_plural': 'Подписчики',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название блюда')),
                ('description', models.TextField(verbose_name='Описание Блюда')),
                ('cooking_method', models.TextField(verbose_name='Способ приготовления')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('calories', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Калорийность')),
                ('allergy', models.ManyToManyField(related_name='inappropriate_dishes', to='tgbot.allergy', verbose_name='Не подходит для:')),
                ('ingredients', models.ManyToManyField(related_name='dishes', to='tgbot.product', verbose_name='Ингридиенты')),
                ('preferences', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appropriate_dishes', to='tgbot.preference', verbose_name='Подходит для:')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
    ]
