# Generated by Django 4.0.3 on 2022-03-17 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allergy',
            options={'verbose_name': 'Аллергия', 'verbose_name_plural': 'Аллергии'},
        ),
        migrations.AlterModelOptions(
            name='preference',
            options={'verbose_name': 'Предпочтение', 'verbose_name_plural': 'Предпочтения'},
        ),
        migrations.AlterModelOptions(
            name='subscribe',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='allergy',
            field=models.ManyToManyField(blank=True, related_name='subscribes', to='tgbot.allergy', verbose_name='Аллергии'),
        ),
    ]
