# Generated by Django 4.0.3 on 2022-03-17 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_alter_allergy_options_alter_preference_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='dish',
            field=models.ManyToManyField(related_name='dishes', to='tgbot.dish', verbose_name='Блюда'),
        ),
    ]
