# Generated by Django 4.0.3 on 2022-03-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_subscribe_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='dish',
            field=models.ManyToManyField(blank=True, related_name='dishes', to='tgbot.dish', verbose_name='Блюда'),
        ),
    ]
