# Generated by Django 4.0.3 on 2022-03-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0005_user_favorite_dishes_user_unloved_dishes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite_dishes',
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_dishes',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite', to='tgbot.dish', verbose_name='Любимые блюда'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='unloved_dishes',
        ),
        migrations.AddField(
            model_name='user',
            name='unloved_dishes',
            field=models.ManyToManyField(blank=True, default=None, related_name='unloved', to='tgbot.dish', verbose_name='Нелюбимые блюда'),
        ),
    ]
