# Generated by Django 4.0.3 on 2022-03-18 02:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0007_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='subscription_period',
        ),
        migrations.AddField(
            model_name='subscribe',
            name='sub_type',
            field=models.CharField(choices=[(1, 1), (3, 3), (6, 6), (9, 9), (12, 12)], db_index=True, default=12, max_length=25, verbose_name='Тип подписки'),
        ),
        migrations.AddField(
            model_name='subscribe',
            name='subscription_start',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Подписка была приобретена'),
        ),
    ]
