# Generated by Django 4.0.3 on 2022-03-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0009_alter_subscribe_sub_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='persons_quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Количество человек, на которых должна быть рассчитана порция'),
        ),
    ]
