# Generated by Django 4.0.3 on 2022-03-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0010_subscribe_persons_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='dish',
        ),
        migrations.AddField(
            model_name='subscribe',
            name='shown_dishes',
            field=models.ManyToManyField(blank=True, related_name='used_subscribes', to='tgbot.dish', verbose_name='Показанные блюда'),
        ),
    ]
