# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: cd to work directory
        run: cd /home/django/code/food-plan-service
      - name: update repo
        run: git pull
      - name: activate python
        run: source env/bin/activate
      - name: migrate
        run: python manage.py makemigrations
      - name: restart apps
        run: sudo systemctl restart food.socket food.service foodbot.service

