name: Python application

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: login
        uses: appleboy/ssh-action@0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
      - name: updat_deploy
        script: |
        cd /home/django/code/food-plan-service
        git pull
        source env/bin/activate
        python manage.py migrate
        sudo systemctl restart food.socket food.service foodbot.service
        echo: successful deployment

