name: Python application

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: login
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
      - name: updat_deploy
        run: cd /home/django/code/food-plan-service
      - name: pull changes
        run: git pull
      - name: activate python
        run:  source env/bin/activate
      - name: migrate
        run:  python manage.py migrate
      - name: reload daemons
        run:  sudo systemctl restart food.socket food.service foodbot.service

