name: Python application

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: login
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
      - name: make dir tests
        run: mkdir tests
      - name: go to tests dir
        run: cd tests
      - name: clone repo
        run: git clone git@github.com:IlyaG96/food-plan-service.git
      - name: activate python
        run:  source env/bin/activate
      - name: migrate
        run:  python manage.py migrate
      - name: reload daemons
        run:  sudo systemctl restart food.socket food.service foodbot.service

