name: Python application

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: list dir
        run: ls
      - name: on which PC i am?
        run: pwd
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: update repo
        run: git pull
      - name: migrate
        run: python manage.py makemigrations
      - name: restart apps
        run: sudo systemctl restart food.socket food.service foodbot.service

