name: Python application

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: list dir
        run: ls
      - name: cd to work directory
        run: cd /home/django/code/food-plan-service
      - name: update repo
        run: git pull
      - name: activate python
        run: source env/bin/activate
      - name: migrate
        run: python manage.py makemigrations
      - name: restart apps
        run: sudo systemctl restart food.socket food.service foodbot.service

